spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buscast
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  bus:
    key: ${BUS_LOCATION_API_KEY}