spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buscast
    username: buscast
    password: postgres
  jackson:
    time-zone: Asia/Seoul


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.jdbc.time_zone: Asia/Seoul

external:
  bus:
    key: ${BUS_LOCATION_API_KEY}